/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testprojekt;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Ludwig Ersson
 */
public class NewCategoryWindow extends javax.swing.JFrame {
    InfDB idb; 
   
    /**
     * Creates new form NewCategoryWindow
     */
    public NewCategoryWindow() {
        initComponents();
        setLocationRelativeTo(this); 
        idb = TestProjekt.getDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCategoryName = new javax.swing.JTextField();
        lblAddNewCategory = new javax.swing.JLabel();
        btnAddNewCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCategoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryNameActionPerformed(evt);
            }
        });

        lblAddNewCategory.setText("Lägg till ny kategori");

        btnAddNewCategory.setText("Lägg till");
        btnAddNewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCategoryName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddNewCategory))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddNewCategory)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblAddNewCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewCategory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCategoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryNameActionPerformed
        
    }//GEN-LAST:event_txtCategoryNameActionPerformed

    private void btnAddNewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCategoryActionPerformed
        String newCategory = txtCategoryName.getText();
        
        

        try {
            
          if (idb.fetchSingle("SELECT COUNT (*) FROM KATEGORI where namn = '" +newCategory +"';").equals("1")){
               JOptionPane.showMessageDialog(null, "Kategorin finns redan tillagd!");
          }
          
          
          else { 
             
            int kaid = 0;  
            if (idb.fetchSingle("SELECT count (*) FROM KATEGORI").equals("0")) {
            kaid = 1;
          }
            else {
            String maxKaid = idb.fetchSingle("SELECT max (kaid) FROM KATEGORI");
            System.out.println(maxKaid);
            

            int maxKaidInt = Integer.parseInt(maxKaid);
            kaid = maxKaidInt + 1; 

            System.out.println(kaid);
            
            
            }
            String query = "insert into Kategori (KAID, Namn) values (" + kaid + ", '" + newCategory + "')";

            idb.insert(query);

            
            
            this.dispose();
          }
    

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAddNewCategoryActionPerformed

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCategory;
    private javax.swing.JLabel lblAddNewCategory;
    private javax.swing.JTextField txtCategoryName;
    // End of variables declaration//GEN-END:variables
}
